### PR TITLE
Laird Wifi

### PR DESCRIPTION
**Pull request by matinlotfali**
This pull request adds a layer for Laird Sterling LWB5+ WiFi module

### CODE REVIEW

**Review by mistyron — CHANGES_REQUESTED** [review]
Please add a description about the changes in this PR on the Conversation tab

**Review by mistyron — COMMENTED** [review]
Please check if https://github.com/mistysom/meta-mistylwb5p needs to be updated

**Comment by matinlotfali** [comment]
> Please check if https://github.com/mistysom/meta-mistylwb5p needs to be updated

When reading the difference, I can see that it only affects the bluetooth on lwb5p and not WiFi.

**Review by mistyron — APPROVED** [review]
LGTM

**Pull request merged**
